#!/usr/bin/env ruby

require 'chef'
require 'chef/idm'

# Set the chef group membership for the Chef Org
def set_chef_group_membership(cheforg,chef_group_cname,member_cnames)
  puts "  Setting chef group #{chef_group_cname} members to #{member_cnames}"
end

# Process the AD groups for the Chef Org
def process_chef_org_group_dname(cheforg, group_dname)
  member_cnames=[]
  member_dnames = Chef::Idm::Ldap::Group.members(group_dname)
  member_dnames.each do |member_dname|
    puts "  Found #{member_dname}"
    member_cnames << Chef::Idm::Ldap::User.cname(member_dname)
  end
  chef_group_cname = Chef::Idm::Ldap::Group.cname(group_dname)
  set_chef_group_membership(cheforg, chef_group_cname, member_cnames)
end

# Process a Chef Org
def process_chef_org(cheforg, orgparams)
  orgparams['groups'].each do |group_dname|
    puts "Processing ChefOrg #{cheforg} ADGroup #{group_dname}"
    process_chef_org_group_dname(cheforg, group_dname)
  end
end

# Loop through Chef Organisations
Chef::Idm.config.organizations.each do |cheforg,orgparams|
  process_chef_org(cheforg, orgparams)
end