#!/usr/bin/env ruby

require 'chef'
require 'chef/idm'


# Process a Chef Org
def process_chef_org(cheforg, orgparams)
  puts "  users from Chef org #{cheforg}"
  allowed_users = Chef::Idm.ldap_group(orgparams['allowed']).member_dnames
  allowed_users.each do |dname|
    user = Chef::Idm.ldap_user(dname)
    Chef::Idm.chefglobal.user_update(
      user.cname,
      user.first_name,
      user.middle_name,
      user.last_name,
      user.display_name,
      user.email
    )
  end
end


# Loop through Chef Organisations
puts "Updating chef users from LDAP"
Chef::Idm.config.organizations.each do |cheforg, orgparams|
  process_chef_org(cheforg, orgparams)
end
