#!/usr/bin/env ruby

require 'chef'
require 'chef/idm'

# Process the AD groups for the Chef Org
def process_chef_org_group(cheforg, chefgroup, adgroup)
  ldap_cnames = Chef::Idm.ldap_group(adgroup).member_cnames
  puts "  Setting Chef group #{chefgroup} users #{ldap_cnames}"
  Chef::Idm.cheforg(cheforg).group_set_users(chefgroup,ldap_cnames)
end

# Process a Chef Org
def process_chef_org(cheforg, orgparams)
  orgparams['groups'].each do |chefgroup, adgroup|
    puts "Processing ChefOrg #{cheforg} ChefGroup #{chefgroup} ADGroup #{adgroup}"
    process_chef_org_group(cheforg, chefgroup, adgroup)
  end
end


# Loop through Chef Organisations
Chef::Idm.config.organizations.each do |cheforg, orgparams|
  process_chef_org(cheforg, orgparams)
end

require 'pry'; binding.pry
puts 'Done'